security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User: 'auto'

    providers:
        database_users:
            entity: { class: App\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            lazy: true
            provider: database_users
            form_login:
                check_path: security_login
                login_path: security_login
                enable_csrf: true
                default_target_path: blog_index

            logout:
                path: security_logout
                target: homepage

            entry_point: 'form_login'

    access_control:
        - { path: '^/(%app_locales%)/admin', roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

when@test:
    security:
        firewalls:
            main:
                http_basic: ~
